#  Assistance Backbone for the assistance system developed as part of the VerDatAs project
#  Copyright (C) 2022-2024 TU Dresden (Maximilian Brandt, Robert Schmidt, Sebastian Kucharski)
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

version: '3.8'

services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: app
    user: "33:33"
    environment:
      - MONGO_DB_HOST=mongo
      - MONGO_DB_PORT=27017
      - OLLAMA_URL="ollama:11434"
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - mongo
  mongo:
    image: mongo:5.0.2
    container_name: mongo
    expose:
      - "27017"
    networks:
      - app-network
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    volumes:
      - type: volume
        source: mongo-data
        target: /data/db
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]
  mongo_init:
    image: mongo:5.0.2
    container_name: mongo-init
    restart: "no"
    networks:
      - app-network
    depends_on:
      mongo:
        condition: service_healthy
    command: >
      mongo --host mongo:27017 --eval 
      '
      db = (new Mongo("mongo:27017")).getDB("test");
      config = {
      "_id" : "dbrs",
      "members" : [
        {
          "_id" : 0,
          "host" : "mongo:27017"
        }
      ]
      };
      rs.initiate(config);
      '
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    volumes:
      - type: volume
        source: ollama-data
        target: /root/.ollama
    expose:
      - "11434"
    networks:
      - app-network

volumes:
  mongo-data:
  ollama-data:

networks:
  app-network: