"""
    Assistance Backbone for the assistance system developed as part of the VerDatAs project
    Copyright (C) 2022-2024 TU Dresden (Max Schaible, Sebastian Kucharski)

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

    TUD Assistance Backbone API

    Component for analyzing learning process data in the form of xAPI statements and providing feedback to learners' interactions and assistance and suggestions with regard to the user's learning state and the corresponding learning content.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional

from pydantic import BaseModel, Field, StrictStr, field_validator

from model.api.assistance_parameter import AssistanceParameter

try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class AssistanceObjectRecord(BaseModel):
    """
    Schema for representing a container object that holds assistance data that were processed during an assistance process. It either can represent an `AssistanceObject` or an `AssistanceResponseObject`.
    """  # noqa: E501
    a_id: StrictStr = Field(description="The ID that uniquely identifies the assistance process.", alias="aId")
    type: StrictStr = Field(description="The kind of object this record represents.")
    ao_id: StrictStr = Field(description="The unique ID of an Assistance Object.", alias="aoId")
    user_id: StrictStr = Field(description="The ID of the user the assistance is provided to.", alias="userId")
    assistance_type: Optional[StrictStr] = Field(default=None,
                                                 description="The key of the corresponding assistance type.",
                                                 alias="assistanceType")
    timestamp: StrictStr = Field(description="The timestamp when the assistance was initiated.")
    parameters: List[AssistanceParameter] = Field(description="A list of parameters of the AO.")
    __properties: ClassVar[List[str]] = ["aId", "type", "aoId", "userId", "assistanceType", "timestamp", "parameters"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in ('assistance_object', 'assistance_response_object'):
            raise ValueError("must be one of enum values ('assistance_object', 'assistance_response_object')")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AssistanceObjectRecord from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in parameters (list)
        _items = []
        if self.parameters:
            for _item in self.parameters:
                if _item:
                    _items.append(_item.to_dict())
            _dict['parameters'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of AssistanceObjectRecord from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "aId": obj.get("aId"),
            "type": obj.get("type"),
            "aoId": obj.get("aoId"),
            "userId": obj.get("userId"),
            "assistanceType": obj.get("assistanceType"),
            "timestamp": obj.get("timestamp"),
            "parameters": [AssistanceParameter.from_dict(_item) for _item in obj.get("parameters")] if obj.get(
                "parameters") is not None else None
        })
        return _obj
