"""
    Assistance Backbone for the assistance system developed as part of the VerDatAs project
    Copyright (C) 2022-2024 TU Dresden (Max Schaible, Sebastian Kucharski)

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

    TUD Assistance Backbone API

    Component for analyzing learning process data in the form of xAPI statements and providing feedback to learners' interactions and assistance and suggestions with regard to the user's learning state and the corresponding learning content.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional

from pydantic import BaseModel, Field, StrictBool, StrictStr
from typing_extensions import Annotated

try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class LearningPathElement(BaseModel):
    """
    Schema for representing an element of a learning path.
    """  # noqa: E501
    learning_path_element_id: Optional[StrictStr] = Field(default=None,
                                                          description="The ID of the learning path element that is unique per learning path.",
                                                          alias="learningPathElementId")
    learning_path_element_target: StrictStr = Field(
        description="The ID of the element that is represented by the learning path element e.g., a content page.",
        alias="learningPathElementTarget")
    step: Annotated[int, Field(strict=True, ge=1)] = Field(
        description="The step number of the element within the corresponding learning path.")
    preferred: Optional[StrictBool] = Field(default=None,
                                            description="Whether the learning path element is preferred or not.")
    learning_path_element_processed_requirements: Optional[List[LearningPathElement]] = Field(default=None,
                                                                                              description="A number of learning path elements that have to be processed when this element is processed.",
                                                                                              alias="learningPathElementProcessedRequirements")
    learning_path_element_not_processed_requirements: Optional[List[LearningPathElement]] = Field(default=None,
                                                                                                  description="A number of learning path elements that must not have been processed when this element is processed.",
                                                                                                  alias="learningPathElementNotProcessedRequirements")
    __properties: ClassVar[List[str]] = ["learningPathElementId", "learningPathElementTarget", "step", "preferred",
                                         "learningPathElementProcessedRequirements",
                                         "learningPathElementNotProcessedRequirements"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of LearningPathElement from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in learning_path_element_processed_requirements (list)
        _items = []
        if self.learning_path_element_processed_requirements:
            for _item in self.learning_path_element_processed_requirements:
                if _item:
                    _items.append(_item.to_dict())
            _dict['learningPathElementProcessedRequirements'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in learning_path_element_not_processed_requirements (list)
        _items = []
        if self.learning_path_element_not_processed_requirements:
            for _item in self.learning_path_element_not_processed_requirements:
                if _item:
                    _items.append(_item.to_dict())
            _dict['learningPathElementNotProcessedRequirements'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of LearningPathElement from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "learningPathElementId": obj.get("learningPathElementId"),
            "learningPathElementTarget": obj.get("learningPathElementTarget"),
            "step": obj.get("step"),
            "preferred": obj.get("preferred"),
            "learningPathElementProcessedRequirements": [LearningPathElement.from_dict(_item) for _item in obj.get(
                "learningPathElementProcessedRequirements")] if obj.get(
                "learningPathElementProcessedRequirements") is not None else None,
            "learningPathElementNotProcessedRequirements": [LearningPathElement.from_dict(_item) for _item in obj.get(
                "learningPathElementNotProcessedRequirements")] if obj.get(
                "learningPathElementNotProcessedRequirements") is not None else None
        })
        return _obj


# TODO: Rewrite to not use raise_errors
LearningPathElement.model_rebuild(raise_errors=False)
